version: '3.8'

services:
  sandbox:
    build:
      context: ..
      dockerfile: sandbox/Dockerfile
    image: coderushoj/sandbox:latest
    container_name: coderushoj-sandbox
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ./sandbox-config.yaml:/app/sandbox-config.yaml
    environment:
      - SANDBOX_PORT=8090
      - SANDBOX_HOST=0.0.0.0
      - SANDBOX_MAX_CONCURRENCY=10
      - DOCKER_NETWORK_MODE=none
      - DOCKER_DISABLE_CACHE=true
      - DOCKER_TIMEOUT=10
      - DOCKER_MAX_MEMORY=256
      - DOCKER_CPU_LIMIT=0.5
      - SECURITY_DISABLE_FORK=true
      - SECURITY_DISABLE_NETWORK=true
      - SECURITY_MAX_PROCESSES=50
    networks:
      - coderushoj-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8090/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  coderushoj-network:
    driver: bridge